module.exports = [
  {
    id: 1,
    date: '03/31/2022',
    item_name: 'Salary',
    amount: 8899,
    from: 'Google',
    category: 'Paycheck',
    type: 'income',
  },
  {
    id: 2,
    date: '04/15/2022',
    item_name: 'Airline ticket',
    amount: 600,
    from: 'American Airline',
    category: 'Vacation',
    type: 'expense',
  },
  {
    id: 3,
    date: '04/20/2022',
    item_name: 'Pet food',
    amount: 25,
    from: 'Petco',
    category: 'Shopping',
    type: 'expense',
  },
  {
    id: 4,
    date: '04/24/2022',
    item_name: 'Food shopping',
    amount: 90,
    from: 'Keyfood',
    category: 'Shopping',
    type: 'expense',
  },
  {
    id: 5,
    date: '05/8/2022',
    item_name: 'Oil change',
    amount: 180,
    from: 'Toyota',
    category: 'Car maintenance',
    type: 'expense',
  },
];
